version: '3.9'
services:
  app:
    image: taye97/pythonapp2:staging
    ports:
      - "8087:5000"
    container_name: pythonapp_staging
    environment:
      - ENV=staging
    networks:
      - staging_net
networks:
  staging_net: 
