apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp2
  template:
    metadata:
      labels:
        app: pythonapp2
    spec:
      containers:
        - name: pythonapp
          image: taye97/pythonapp2:${IMAGE_TAG}  
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: "production"
