apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
spec:
  type: NodePort
  selector:
    app: pythonapp2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30886  
